INSERT INTO EASY_TASK(STATEMENT) VALUES('テスト');
INSERT INTO EASY_TASK(STATEMENT) VALUES('課題');
INSERT INTO EASY_TASK(STATEMENT) VALUES('おにやんま');
INSERT INTO EASY_TASK(STATEMENT) VALUES('かえる');
INSERT INTO EASY_TASK(STATEMENT) VALUES('らっきー');
